scraper:
  base_url: "https://fbref.com/en/comps"
  league_ids:
    Premier-League: "9"
    Bundesliga: "20"
  output_dir: "raw"
  sleep_range: [30,40]
  max_retries: 3
  retry_delay: 60
  player_data: false

#note: vars -> variables to omit from the FBRef player table
pre-process: 
  vars:
    - Gls
    - Ast
    - Min
    - Ast

root_dir: /Users/paraspokharel/Programming/pitchProphet/pitchProphet
raw_Fdata: data/fbref/trial90.json