# note: vars -> variables to omit from the FBRef player table
get-data:
  league: Premier-League
  season: 2023-2024
  league_code:
    Premier-League: 9
    Bundesliga: 20

pre-process: 
  vars:
    - Gls
    - Ast
    - Min
    - Ast

root_dir: /Users/paraspokharel/Programming/pitchProphet/pitchProphet
raw_Fdata: data/fbref/trial90.json

scraper:
  base_url: "https://fbref.com/en/comps"
  league_ids:
    Premier-League: "9"
    Bundesliga: "20"
  output_dir: "data/fbref"
  sleep_range: [10, 15]
  max_retries: 3
  retry_delay: 60
