test:
  - arrayVal1
  - arrayVal2

global:
  - league: 
    - Premier League
  - season:  
    - 2023-24
    - 2022-23

player:
  - Name
  - Shirt number
  - Nationality
  - Position played
  - Age
  - Minutes played
  - Goals scored
  - Assists
  - Penalty kicks attempted and scored
  - Total shots and shots on target
  - Yellow and red cards
  - Total touches
  - Total tackles
  - Total interceptions
  - Total blocks
  - Expected goals scored (XG)
  - Expected goals scored without penalty kicks
  - Expected assists
  - Total passes attempted, completed
  - Progressive passes
  - Total carries and progressive carries
  - Total attacks and successful attacks

goalkeeper: 
  - Total shots saved
  - Save percentage
  - Post shot expected goals conceded
  - Total passes attempted
  - Average legnth of pass
  - Total goal kicks
  - Average length of goal kicks
  - Tota crosses faced and stopped
  - Total defensive actions outside the penalty box

url:
   - https://fbref.com/en/comps/9/Premier-League-Stats#all_stats_squads_passing
   
